<a href="https://colab.research.google.com/github/sanvadds/Python-Basic-Practice/blob/main/Numpy_Stack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a= np.array([[1,2,3],[4,5,6]])
print("This is A Array...")
print(a)
print("\n")


b = np.array([[10,20,30],[40,50,60]])
print("This is B Array....")
print(b)
print("\n")

print("This is Verticle Stack..")
print(np.vstack([a,b]))

print("\n This is Horizontal Stack...")
print(np.hstack([a,b]))

This is A Array...
[[1 2 3]
 [4 5 6]]


This is B Array....
[[10 20 30]
 [40 50 60]]


This is Verticle Stack..
[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]

 This is Horizontal Stack...
[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]
