<a href="https://colab.research.google.com/github/sanvadds/Python-Basic-Practice/blob/main/Numpy_practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
n1=np.array([[10,20],[30.2,40]])
print(n1)

[[10.  20. ]
 [30.2 40. ]]


In [4]:
n2=np.zeros([5,3])
print(n2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
n3=np.full([2,3],5)
print(n3)

[[5 5 5]
 [5 5 5]]


In [6]:
n4 = np.arange(0,20,4)
print(n4)

[ 0  4  8 12 16]


In [7]:
n5 = np.random.randint(1,25,(3,3))
print(n5)
print(n5[0,:])

[[11  4 12]
 [10 10 23]
 [ 7 11 15]]
[11  4 12]


In [8]:
n1=np.random.randint(1,50,[3,3])
print(n1)

[[12 25 10]
 [23 40 29]
 [28 27 14]]


In [9]:
print(n1.shape)

(3, 3)


In [13]:
n2 = np.random.randint(50,100,[3,3])
print("n2 : ")
print(n2)
np.vstack((n1,n2))
print("n1 : ")
print(n1)

n2 : 
[[58 55 61]
 [58 77 62]
 [73 78 92]]
n1 : 
[[12 25 10]
 [23 40 29]
 [28 27 14]]


In [14]:
np.hstack((n1,n2))
print(n1)

[[12 25 10]
 [23 40 29]
 [28 27 14]]


In [15]:
print(np.column_stack((n1,n2)))

[[12 25 10 58 55 61]
 [23 40 29 58 77 62]
 [28 27 14 73 78 92]]


In [35]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90,100])


print("Intersect \t\t\t : ",np.intersect1d(n1,n2))
print("Set difference n1 - n2 \t\t : ",np.setdiff1d(n1,n2))
print("Set difference n2 - n1 \t\t : ",np.setdiff1d(n2,n1))
print("Union \t\t\t\t : ",np.union1d(n1,n2))

Intersect 			 :  [50 60]
Set difference n1 - n2 		 :  [10 20 30 40]
Set difference n2 - n1 		 :  [ 70  80  90 100]
Union 				 :  [ 10  20  30  40  50  60  70  80  90 100]


**SAVE AND LOAD NUMPY ARRAY**

In [36]:
n1 = np.array([10,20,30,40,50])
np.save('numpy_array',n1)

n2=np.load('numpy_array.npy')
print(n2)

[10 20 30 40 50]
